### member create
POST http://localhost:8080/members
Content-Type: application/json

{
  "email": "gomotest3@naver.com",
  "password": "Test123@",
  "handle": "@GOMOTEST3",
  "name": "gomotest3",
  "motto": "TEST MOTTO",
  "loginProvider": "EMAIL"
}

### member login
POST http://localhost:8080/members/login
Content-Type: application/json

{
  "email": "gomotest3@naver.com",
  "password": "Test123@"
}

### member logout
GET http://localhost:8080/members/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMTk5NDJiNC1mMDA3LTc0MGQtYTZlNy04ZjMwZWE4MWQ0NWUiLCJpYXQiOjE3NTc4NTcwOTIsImV4cCI6MTc1Nzg1Nzk5Mn0.iAyRCvxbHrsbQGkzquobN1or_uFsmWJgyn9fNtH2Pjg
Content-Type: application/json

### interest create
POST http://localhost:8080/interests/01993c30-3d40-72b4-84e2-b431931338ed/majors
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMTk5M2NiMy0yMTYxLTc1MTEtOGE5YS02NDcyZGM1ODJhZGUiLCJpYXQiOjE3NTc3NTM4MjQsImV4cCI6MTc1Nzc1NDcyNH0.5iD2Othjvr5diGpTKr4t1p58r5rLfU4T7CkCTi7kWjQ
Content-Type: application/json
