DELETE FROM member;

INSERT INTO member (
    id,
    email,
    password,
    profile_image_url,
    profile_image_origin_name,
    handle,
    name,
    motto,
    daily_quest_threshold,
    weekly_quest_threshold,
    monthly_quest_threshold,
    role_type,
    subscription_plan,
    activate_status,
    sign_up_date_time,
    created_at,
    created_by,
    last_modified_at,
    last_modified_by,
    deleted_at
) VALUES (
    UNHEX(REPLACE('a10581ce-d721-11ef-a8a5-2508e2a6438b', '-', '')),
    'gomotest@naver.com',
    'gomotest1234@',
    'https://mini-cloud/gomotest-profile',
    'gomotest-profile.png',
    '@GOMOTEST',
    'gomotest',
    'gomotest fighting!',
    10,
    5,
    3,
    'ROLE_MEMBER',
    'FREE',
    'ACTIVE',
    '2025-01-20T20:36:37.591469',
    '2025-01-20T20:36:37.591469',
    'gomotest@naver.com',
    '2025-01-20T20:36:37.591469',
    'gomotest@naver.com',
    null
);