DELETE FROM member;

-- 전날 로그인을 한 사용자는 테스트 실행 시점의 날짜로 데이터를 생성해야한다.
-- global_variables 테이블을 활용해 현재 시간을 공통으로 관리하고 세션 변수에 할당해 사용한다.
SET @current_date_time = (SELECT value FROM global_variables WHERE name = 'current_date_time');

INSERT INTO member (
    id,
    email,
    password,
    profile_banner_url,
    profile_image_url,
    handle,
    name,
    motto,
    daily_quest_threshold,
    weekly_quest_threshold,
    monthly_quest_threshold,
    login_provider,
    role_type,
    subscription_plan,
    activate_status,
    sign_up_date_time,
    last_login_date_time,
    created_at,
    created_by,
    last_modified_at,
    last_modified_by,
    deleted_at
) VALUES
      (UNHEX(REPLACE('a10581ce-d721-11ef-a8a5-2508e2a6438b', '-', '')),
       'gomotest@naver.com',
       '$2a$10$jlCrDrKargI8AhuSrS4FOuOX6e0w9a0F63/Norho6TGefGuljB2WC',
       'https://mini-cloud/gomotest-profile',
       'https://mini-cloud/gomotest-profile',
       '@GOMOTEST',
       'gomotest',
       'gomotest fighting!',
       10,
       5,
       0, -- create quest document test: 생성 제한 테스트를 위해 임계치를 0으로 고정한다.
       'EMAIL',
       'ROLE_MEMBER',
       'FREE',
       'ACTIVE',
       @current_date_time,
       @current_date_time,
       @current_date_time,
       'a10581ce-d721-11ef-a8a5-2508e2a6438b',
       @current_date_time,
       'a10581ce-d721-11ef-a8a5-2508e2a6438b',
       null),

      (UNHEX(REPLACE('a10581ce-d721-11ef-a8a5-250872a6438b', '-', '')),
       'gomotest2@naver.com',
       '$2a$10$jlCrDrKargI8AhuSrS4FOuOX6e0w9a0F63/Norho6TGefGuljB2WC',
       'https://mini-cloud/gomotest-profile',
       'https://mini-cloud/gomotest-profile',
       '@GOMOTEST2',
       'gomotest',
       'gomotest fighting!',
       7,
       7,
       7,
       'EMAIL',
       'ROLE_MEMBER',
       'FREE',
       'ACTIVE',
       @current_date_time,
       @current_date_time,
       @current_date_time,
       'a10581ce-d721-11ef-a8a5-2508e2a6438b',
       @current_date_time,
       'a10581ce-d721-11ef-a8a5-2508e2a6438b',
       null);