=== 회원 가입

`POST /auth/signup`

새로운 회원을 생성합니다.

==== 요청 헤더

operation::auth-signup[snippets='request-headers']

==== 요청 본문 (JSON)

operation::auth-signup[snippets='http-request,request-fields']

==== 성공 응답

operation::auth-signup[snippets='http-response,response-fields']

'''

=== 비밀번호 초기화 (찾기)

`PUT /auth/passwords/reset`

이메일 인증 등을 통해 본인인증이 완료된 사용자가 비밀번호를 새로 설정합니다.

==== 요청 헤더

operation::auth-password-reset[snippets='request-headers']

==== 요청 본문 (JSON)

operation::auth-password-reset[snippets='http-request,request-fields']

==== 성공 응답

성공 시 `204 No Content` 상태 코드와 함께 빈 응답 본문을 반환합니다.

'''

=== 로그인

`POST /auth/login`

이메일과 비밀번호로 로그인하여 인증 토큰을 발급받습니다.

==== 요청 헤더

operation::auth-login[snippets='request-headers']

==== 요청 본문 (JSON)

operation::auth-login[snippets='http-request,request-fields']

==== 성공 응답

operation::auth-login[snippets='http-response,response-fields']

'''

=== 로그아웃

`GET /auth/logout`

현재 로그인된 사용자의 세션을 종료하고 인증 토큰을 무효화합니다.

==== 요청 헤더

operation::auth-logout[snippets='request-headers']

==== 성공 응답

성공 시 `204 No Content` 상태 코드와 함께 빈 응답 본문을 반환합니다.

'''

=== Refresh Token 재발급

`POST /auth/refresh`

만료된 Access Token을 재발급받습니다. 요청 시 유효한 `refreshToken`을 쿠키에 담아 전송해야 합니다.

==== 요청 헤더

operation::auth-update-refresh-token[snippets='request-headers']

==== 요청 쿠키

operation::auth-update-refresh-token[snippets='request-cookies']

==== 성공 응답

operation::auth-update-refresh-token[snippets='http-response,response-fields']

'''

=== 이메일 인증 코드 발송 (회원 가입)

`POST /auth/codes/emails/signup`

회원가입에 사용할 이메일 인증 코드를 요청한 이메일 주소로 발송합니다.

==== 요청 헤더

operation::auth-code-for-sign-up-create[snippets='request-headers']

==== 요청 본문 (JSON)

operation::auth-code-for-sign-up-create[snippets='http-request,request-fields']

==== 성공 응답

성공 시 `201 Created` 상태 코드와 함께 빈 응답 본문을 반환합니다.

==== 에러 응답 (이미 가입된 이메일)

operation::auth-code-for-sign-up-create-error[snippets='http-response,response-fields']

'''

=== 이메일 인증 코드 발송 (비밀번호 변경 시)

`POST /auth/codes/emails/passwords/reset`

비밀번호 찾기에 사용할 이메일 인증 코드를 요청한 이메일 주소로 발송합니다.

==== 요청 헤더

operation::auth-code-for-password-reset-create[snippets='request-headers']

==== 요청 본문 (JSON)

operation::auth-code-for-password-reset-create[snippets='http-request,request-fields']

==== 성공 응답

성공 시 `201 Created` 상태 코드와 함께 빈 응답 본문을 반환합니다.

==== 에러 응답 (이미 가입된 이메일)

operation::auth-code-for-password-reset-create-error[snippets='http-response,response-fields']

'''

=== 이메일 인증 코드 검증

`GET /auth/codes/emails/verify`

이메일로 발송된 인증 코드가 올바른지 검증합니다.

==== 쿼리 파라미터

operation::auth-code-verify[snippets='query-parameters']

==== 성공 응답

인증 성공 시, `200 OK` 상태 코드와 함께 빈 응답 본문을 반환합니다.

==== 에러 응답 (잘못된 인증 코드)

operation::auth-code-verify-error[snippets='http-response,response-fields']
